[ETC] JS 100제 / 66~67번 / HyejinLee
TEAM-BraveLion14/coding-test pull request #33
Opened 2022-11-09 10:44 UTC by hyelight

2022-11-09 11:25 UTC, dev-yun approved these changes
아이디어가 좋습니다!

2022-11-09 11:26 UTC, SEMINSEMINSEMIN requested changes
코드 수정해주세욤!!

2022-11-09 11:37 UTC, SEMINSEMINSEMIN approved these changes
66번 문자랑 규칙이랑 비교한다는 아이디어가 넘 깔끔하고 좋은거같아요!

2022-11-10 06:55 UTC, dev-yun approved these changes
코드가 깔끔하네요 !

2022-11-10 06:57 UTC, merged